use_frameworks!

target 'GradualEffect_Example' do
  pod 'GradualEffect', :path => '../'

  target 'GradualEffect_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
